name:               "Yan Sun"
description:        "PhD student @ King's College London"

url:                "http://ysun94.github.io"
author:             "ysun94"
email:              "yan.sun@kcl.ac.uk"
gravatar_hash:      "1fb240082fd27943ca9907574ba4b95f"
twitter:            #"jhondoe"
email:              "yan.sun@kcl.ac.uk"
github:             "ysun94"
pinterest:          # "jhondoe"
linkedin:           # "jhondoe"
facebook:           # "jhondoe"

disqus_shortname:   "ysun94"

background:         "http://ysun94.github.io/assets/images/IMG_0105.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          :year/:month/:de5c7e08016aeaa80d78eacbc33d60ccday/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "about"
  - name:           "Download"
    href:           "releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
