name:               "Yan Sun"
description:        "PhD student at King's College London"

url:                "ysun94.github.io"
author:             "Yan Sun"
email:              "yan.sun@kcl.ac.uk"
gravatar_hash:      "1fb240082fd27943ca9907574ba4b95f"
twitter:            # "jhondoe"
email:              "yan.sun@kcl.ac.uk"
github:             "ysun94"
pinterest:          # "jhondoe"
linkedin:           # "jhondoe"
facebook:           # "jhondoe"

disqus_shortname:   "ysun94"

background:         "http://ysun94.github.io/assets/images/IMG_1574.JPG"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
theme: jekyll-theme-cayman
